### ISSUE TITLE
Questions, suggestions, comments and StackOverflow

### ISSUE THREAD

**Issue by usaygij** [newlibertie/server#12]
Ballot.scala:
1. Why number of bits for omega random number needs to be 4 times the CryptographicParameters?
2. Why value assigned to y needs to be .mod(cp.large_prime_p)
3. For positive vote, don’t the values assigned to d2 and r2 need to be made .mod(cp.large_prime_p)?
4. For negative vote, don’t the values assigned to d1 and r1 need to be made .mod(cp.large_prime_p)?
5. In getC() body, why the generated number needs to be made mod(<Some big number>)? Can’t it remain without any mod?
6. If it needs to be made mod(<Some big number>), we can always create that big number once as a val member of CryptographicParameters, for efficiency reason.
7. Take a diff of the code in branch ballot-fixes with code in branch harmindar_cast_ballot. It is a simple change, worth consideration and won’t take much time or effort.
8. Negative vote test gives and exception/error "java.lang.StackOverflowError".

**Comment by vivekpathak** [comment]
https://github.com/newlibertie/server/pull/13

**Comment by vivekpathak** [comment]
fixed and tests show big num example with 1000 bit exponents
